### ISSUE TITLE
Plugin and package.json file no longer required.

### ISSUE THREAD

**Issue by chemzqm** [jsfaint/coc-neoinclude#1]
Coc could regist the source as extension: https://github.com/neoclide/coc.nvim/commit/8223ce7762263361480207412778d1cfd498e04c

**Comment by jsfaint** [comment]
I tested it without plugin direcotry and package.json, it works well.
But one little problem here, the mark became `[NEO]`, how can I fix it?

**Comment by chemzqm** [comment]
Return `shortcut` in `init` like: https://github.com/neoclide/coc-neco/blob/master/autoload/coc/source/neco.vim

**Comment by jsfaint** [comment]
Thanks for your clarify, I modify the init()
but it is weird on my side, I this got this. Did I make some mistake?
![](https://user-images.githubusercontent.com/571829/50369272-8176ec80-05cd-11e9-926c-0ab390451bfb.png)

**Comment by chemzqm** [comment]
You need to build coc.nvim from master branch.

**Comment by jsfaint** [comment]
oh, got it, the feature is not included in the latest release version:grinning:

Thanks again
